## Numpy array and basics


### creating array from list


In [3]:
import numpy as np

In [4]:
arr_1d = np.array ([1, 2, 3, 4, 5])
print ("1D array: ", arr_1d)

arr_2d = np.array ([[1, 2, 3], [4, 5, 6]])
print ("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs Numpy array

In [6]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array ([1, 2, 3])
print("Python list multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python list multiplication  [2 4 6]


## Creating array from scratch

In [11]:
zeros = np.zeros((3,4))
print ("Zeros array: \n", zeros)

ones = np.ones ((3,4))
print ("one array: \n", ones)

full = np.full ((2,2), 7)
print ("full array: \n", full)

random = np.random.random((2,3))
print ("random array: \n", random)

sequence = np.arange(0, 10, 2)
print ("sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[9.25036174e-01 6.44109583e-01 4.57415324e-02]
 [4.64830141e-01 1.50661420e-04 2.18824203e-01]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix & Tensor

In [16]:
vector = np.array([1, 2, 3])
print ("Vector: ", vector )

matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print ("Matrix: ", matrix )

tensor = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
                                    
print ("Tensor: ", tensor )


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Array Properties

In [17]:
arr = np.array ([[1, 2, 3],
                 [4, 5, 6]])

print ("Shape ", arr.shape)
print ("Dimension", arr.ndim)
print ("Size", arr.size)
print ("Dtype", arr.dtype)

Shape  (2, 3)
Dimension 2
Size 6
Dtype int64


## Array Reshaping


In [20]:
arr = np.arange(12)
print ("Original", arr)

reshaped = arr.reshape((3, 4))
print ("\n Reshaped array", reshaped)

flattened = arr.flatten()
print ("\n flattened array", flattened)

# ravel (Returns view instead of copy)
Raveled = arr.ravel()
print ("\n Raveled array", Raveled)

# Transpose
transpose = reshaped.T
print ("\n Transposed array", transpose)







Original [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Numpy Array Operations

In [21]:
import numpy as np

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print ("Basic Slicing", arr[2:7])
print ("with step", arr[1:8:2])
print ("Negative slicing", arr[-3])

Basic Slicing [3 4 5 6 7]
with step [2 4 6 8]
Negative slicing 8


In [26]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print ("Specific Element", arr_2d [1, 2])
print ("Entire Row", arr_2d [1])
print ("Entire Coloum", arr_2d [:, 1])

Specific Element 6
Entire Row [4 5 6]
Entire Coloum [2 5 8]


## Sorting

In [31]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2])
print ("Sorted array ", np.sort(unsorted))

arr_2d_unsorted = np.array ([[3, 1], [1, 2], [2, 3]])
print ("Sorted 2d array by coloum", np.sort(arr_2d_unsorted, axis=0))

Sorted array  [1 1 2 3 4 5 9]
Sorted 2d array by coloum [[1 1]
 [2 2]
 [3 3]]


## Filter


In [32]:
numbers = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers [numbers % 2 == 0]
print ("Even number", even_number)

Even number [ 2  4  6  8 10]


## Filter with mask

In [33]:
mask = numbers > 5
print ("Numbers greater than 5", numbers [mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy Indexing vs np.where ()

In [40]:
indices = [0, 2, 4]
print (numbers [indices])

where_result = np.where (numbers > 5)
print ("NP where", numbers[where_result])

condition_array = np.where (numbers>5, numbers*2, numbers)
print (condition_array)

[1 3 5]
NP where [ 6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [42]:
arr1= np.array([1, 2, 3])
arr2= np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print (combined)

[1 2 3 4 5 6]


## Array Compatibility

In [44]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print ("Compatibility Shapes", a.shape == b.shape)

Compatibility Shapes False


In [46]:
original = np.array ([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack ((original, new_row))
print (original)
print (with_new_row)

new_col = np.array ([[7], [8]])
with_new_col = np.hstack ((original, new_col))
print (with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [47]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr,2)
print (deleted)

[1 2 4 5]
